
....

class A:
    def __init__(self, x, y):
        b = B(x)
        c = C(y)

    def do_something(self, x)
        d = D(x)
        result = d.action()


    def do_another(self):
        ...
        ... <- highly cohesive piece of code
        ...
        
        ...
        ...
        ...

        ...
        ... <- other highly cohesive piece of code
        ...
